{{- if .Values.configMapData }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}-configmap
  namespace: {{ .Values.namespace }}
data: 
  {{ toYaml .Values.configMapData | nindent 12 }}  
{{- end }} 
