{{- if eq .Values.enviroment "production" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.enviroment  }}-deployment-canary
  namespace: {{ .Values.namespace }}
  labels:
    app: application-bankly
    helm-package: bankly-product
    release: {{ .Release.Name }}
    enviroment: {{ .Values.enviroment  }}
spec:
  {{- if eq .Values.isCanary true }}
  replicas: 1
  {{- else }}
  replicas: 0
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
      enviroment: {{ .Values.enviroment  }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        version: canary
        enviroment: {{ .Values.enviroment  }}
    spec:
      serviceAccountName: {{ .Values.service.name }}-{{ .Values.enviroment  }}-serviceAccount
      containers:
        - name: {{ .Values.service.name }}-pod
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}
---
{{- if eq .Values.isCanary false }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.enviroment  }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: application-bankly
    helm-package: bankly-product
    release: {{ .Release.Name }}
    enviroment: {{ .Values.enviroment  }}
spec:
  {{- if or (eq .Values.enviroment "staging") (eq .Values.enviroment "testing") }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
      enviroment: {{ .Values.enviroment  }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        version: safe
        enviroment: {{ .Values.enviroment }}
    spec: 
      serviceAccountName: {{ .Values.service.name }}-{{ .Values.enviroment  }}-serviceAccount
      containers:
        - name: {{ .Values.service.name }}-pod
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
                  
{{- end }}