{{- if eq .Values.environment "production" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.environment  }}-deployment-canary
  namespace: {{ .Values.namespace }}
  labels:
    app: application-bankly
    helm-package: bankly-product
    release: {{ .Release.Name }}
    environment: {{ .Values.environment  }}
   
    context: {{ .Values.tagsResources.context }}
    type: {{ .Values.tagsResources.type }}
    cc: {{ .Values.tagsResources.cc }}
    product: {{ .Values.tagsResources.product }}
spec:
  {{- if eq .Values.isCanary true }}
  replicas: 1
  {{- else }}
  replicas: 0
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
      environment: {{ .Values.environment  }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        version: canary
        environment: {{ .Values.environment  }}
    spec:
      priorityClassName: {{ .Values.priorityClassName }}
  
      {{- if .Values.volumes }}
      volumes:
      {{- toYaml .Values.volumes | nindent 12 }}
      {{- end }}

      {{- if eq .Values.serviceAccount.enabled true }}      
      serviceAccountName: {{ .Values.service.name }}-{{ .Values.environment  }}-serviceaccount
      {{- end }}
      containers:
        - name: {{ .Values.service.name }}-pod
          image: {{ .Values.containerImage }}
          imagePullPolicy: IfNotPresent

          ports:
          - name: http
            containerPort: 80
            protocol: TCP

          {{- if .Values.volumeMounts }}
          volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 12 }}     
          {{- end }}
          
          livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
            
          env:
            - name: SERVICE_NAME
              value: {{ .Values.service.name }}
            - name: SERVICE_VERSION
              value: {{ ( splitList ":" .Values.containerImage ) | last }}

          {{- if eq .Values.environment "staging" }}
            - name: ASPNETCORE_ENVIRONMENT
              value: "Staging"
            - name: NODE_ENV
              value: "staging"
          {{- if .Values.stagingEnvironment }}
          {{- toYaml .Values.stagingEnvironment | nindent 12 }}
          {{- end }}
          {{- end }}
          
          {{- if eq .Values.environment "testing" }}
            - name: ASPNETCORE_ENVIRONMENT
              value: "Testing"
            - name: NODE_ENV
              value: "testing"
          {{- if .Values.testingEnvironment }}
          {{- toYaml .Values.testingEnvironment | nindent 12 }}
          {{- end }}
          {{- end }}
          
          {{- if eq .Values.environment "sandbox" }}
            - name: ASPNETCORE_ENVIRONMENT
              value: "Sandbox"
            - name: NODE_ENV
              value: "sandbox"
          {{- if .Values.sandboxEnvironment }}
          {{- toYaml .Values.sandboxEnvironment | nindent 12 }}
          {{- end }}
          {{- end }}
          
          {{- if eq .Values.environment "production" }}
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: NODE_ENV
              value: "production"
          {{- if .Values.productionEnvironment }}          
          {{- toYaml .Values.productionEnvironment | nindent 12 }}
          {{- end }}      
          {{- end }}         
{{- end }}
---
{{- if eq .Values.isCanary false }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.environment  }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: application-bankly
    helm-package: bankly-product
    release: {{ .Release.Name }}
    environment: {{ .Values.environment  }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
      environment: {{ .Values.environment  }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        version: safe
        environment: {{ .Values.environment }}
    spec:
      priorityClassName: {{ .Values.priorityClassName }}
      {{- if .Values.volumes }}
      volumes:
      {{- toYaml .Values.volumes | nindent 12 }}
      {{- end }}

      {{- if eq .Values.serviceAccount.enabled true }}      
      serviceAccountName: {{ .Values.service.name }}-{{ .Values.environment  }}-serviceaccount
      {{- end }}
      containers:
        - name: {{ .Values.service.name }}-pod
          image: {{ .Values.containerImage }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP 
          
          {{- if .Values.volumeMounts }}
          volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 12 }}     
          {{- end }}

          livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          env:
            - name: SERVICE_NAME
              value: {{ .Values.service.name }}
            - name: SERVICE_VERSION
              value: {{ ( splitList ":" .Values.containerImage ) | last }}

          {{- if eq .Values.environment "staging" }}
            - name: ASPNETCORE_ENVIRONMENT
              value: "Staging"
            - name: NODE_ENV
              value: "staging"
          {{- if .Values.stagingEnvironment }}
          {{- toYaml .Values.stagingEnvironment | nindent 12 }}
          {{- end }}
          {{- end }}
          
          {{- if eq .Values.environment "testing" }}
            - name: ASPNETCORE_ENVIRONMENT
              value: "Testing"
            - name: NODE_ENV
              value: "testing"
          {{- if .Values.testingEnvironment }}
          {{- toYaml .Values.testingEnvironment | nindent 12 }}
          {{- end }}
          {{- end }}
          
          {{- if eq .Values.environment "sandbox" }}
            - name: ASPNETCORE_ENVIRONMENT
              value: "Sandbox"
            - name: NODE_ENV
              value: "sandbox"
          {{- if .Values.sandboxEnvironment }}
          {{- toYaml .Values.sandboxEnvironment | nindent 12 }}
          {{- end }}
          {{- end }}
          
          {{- if (eq .Values.environment "production") }}
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: NODE_ENV
              value: "production"
          {{- if .Values.productionEnvironment }}          
          {{- toYaml .Values.productionEnvironment | nindent 12 }}
          {{- end }}      
          {{- end }}      
{{- end }}