{{- if eq .Values.enviroment "production" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.enviroment  }}-deployment-canary
  namespace: {{ .Values.namespace }}
  labels:
    app: application-bankly
    helm-package: bankly-product
    release: {{ .Release.Name }}
    enviroment: {{ .Values.enviroment  }}
spec:
  {{- if eq .Values.isCanary true }}
  replicas: 1
  {{- else }}
  replicas: 0
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
      enviroment: {{ .Values.enviroment  }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        version: canary
        enviroment: {{ .Values.enviroment  }}
    spec:
      serviceAccountName: {{ .Values.service.name }}-{{ .Values.enviroment  }}-serviceaccount
      containers:
        - name: {{ .Values.service.name }}-pod
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: SERVICE_NAME
            value: {{ .Values.service.name }}
          - name: SERVICE_VERSION
            value: {{ .Values.image.tag }}

          {{- if eq .Values.enviroment "staging" }}
          - name: ASPNETCORE_ENVIRONMENT
            value: "Staging"
          - name: NODE_ENV
            value: "staging"
          {{- toYaml .Values.stagingEnv | nindent 12 }}
          {{- end }}
          
          {{- if eq .Values.enviroment "testing" }}
          - name: ASPNETCORE_ENVIRONMENT
            value: "Test"
          - name: NODE_ENV
            value: "test"          
          {{- toYaml .Values.testingEnv | nindent 12 }}
          {{- end }}  
          
          {{- if eq .Values.enviroment "sandbox" }}
          - name: ASPNETCORE_ENVIRONMENT
            value: "Sandbox"
          - name: NODE_ENV
            value: "sandbox"          
          {{- toYaml .Values.sandboxEnv | nindent 12 }}
          {{- end }}
          
          {{- if eq .Values.enviroment "production" }}
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: NODE_ENV
            value: "production"          
          {{- toYaml .Values.productionEnv | nindent 12 }}
          {{- end }}        
{{- end }}
---
{{- if eq .Values.isCanary false }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.enviroment  }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: application-bankly
    helm-package: bankly-product
    release: {{ .Release.Name }}
    enviroment: {{ .Values.enviroment  }}
spec:
  {{- if or (eq .Values.enviroment "staging") (eq .Values.enviroment "testing") }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
      enviroment: {{ .Values.enviroment  }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        version: safe
        enviroment: {{ .Values.enviroment }}
    spec: 
      serviceAccountName: {{ .Values.service.name }}-{{ .Values.enviroment  }}-serviceaccount
      containers:
        - name: {{ .Values.service.name }}-pod
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: SERVICE_NAME
            value: {{ .Values.service.name }}
          - name: SERVICE_VERSION
            value: {{ .Values.image.tag }}

          {{- if eq .Values.enviroment "staging" }}
          - name: ASPNETCORE_ENVIRONMENT
            value: "Staging"
          - name: NODE_ENV
            value: "staging"

          {{- toYaml .Values.stagingEnv | nindent 12 }}
          {{- end }}
          
          {{- if eq .Values.enviroment "testing" }}
          - name: ASPNETCORE_ENVIRONMENT
            value: "Test"
          - name: NODE_ENV
            value: "test"          

          {{- toYaml .Values.testingEnv | nindent 12 }}
          {{- end }}  
          
          {{- if eq .Values.enviroment "sandbox" }}
          - name: ASPNETCORE_ENVIRONMENT
            value: "Sandbox"
          - name: NODE_ENV
            value: "sandbox"          

          {{- toYaml .Values.sandboxEnv | nindent 12 }}
          {{- end }}
          
          {{- if eq .Values.enviroment "production" }}
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: NODE_ENV
            value: "production"          

          {{- toYaml .Values.productionEnv | nindent 12 }}
          {{- end }}
{{- end }}