apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.service.name }}-{{ .Values.namespace }}-{{ .Values.enviroment  }}-dr
  namespace: {{ .Values.istioGateway.namespace }}
spec:
  host: {{ .Values.service.name }}-{{ .Values.enviroment  }}-service.{{ .Values.namespace }}.svc.cluster.local
  subsets:
  - name: safe
    labels:
      version: safe
  {{- if eq .Values.isCanary true }}
  - name: canary
    labels:
      version: canary
  {{- end }}