{{- if eq .Values.cronjobs.jobOnly false }}
{{- if eq .Values.istioGateway.enable true }} 
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.service.name }}-{{ .Values.namespace }}-{{ .Values.environment  }}-dr
  namespace: {{ .Values.istioGateway.namespace }}
spec:
  host: {{ .Values.service.name }}-{{ .Values.environment  }}-service.{{ .Values.namespace }}.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 10s
      baseEjectionTime: 30s
  subsets:
  - name: safe
    labels:
      version: safe
  {{- if eq .Values.isCanary true }}
  - name: canary
    labels:
      version: canary
  {{- end }}
{{- end }}
{{- end }}
