{{- if or (eq .Values.enviroment "production-region-1") (eq .Values.enviroment "production-region-2") (eq .Values.enviroment "sandbox") }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.service.name }}-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
{{- end }}