apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-{{ .Values.enviroment  }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: application-bankly
    helm-package: bankly-product
    release: {{ .Release.Name }}
    enviroment: {{ .Values.enviroment  }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ .Values.service.name }}