apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: application-bankly
    helm-package: bankly-product
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.service.name }}