{{- if eq .Values.serviceAccount.enabled true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service.name }}-{{ .Values.environment }}-serviceaccount
  namespace: {{ .Values.namespace }}
  annotations:
 
  {{- if eq .Values.environment "staging" }}
    {{- if eq .Values.region "us-east-1" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArnStagingUsEast1 }}
    {{- end }}
    {{- if eq .Values.region "us-west-2" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArnStagingUsWest2 }}
    {{- end }}
  {{- end }}
  
  {{- if eq .Values.environment "testing" }}
    {{- if eq .Values.region "us-east-1" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArnTestingUsEast1 }}
    {{- end }}
    {{- if eq .Values.region "us-west-2" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArnTestingUsWest2 }}
    {{- end }}
  {{- end }}
  
  {{- if eq .Values.environment "sandbox" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArnSandbox }}
  {{- end }}
  
  {{- if eq .Values.environment "production" }}
    {{- if eq .Values.region "us-east-1" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArnProductionUsEast1 }}
    {{- end }}
    {{- if eq .Values.region "us-west-2" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArnProductionUsWest2 }}
    {{- end }}
  {{- end }}    
{{ end }}
                                                                                                                                                                                                                                                                                                