apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-{{ .Values.environment  }}-service
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: application-bankly
    helm-package: bankly-product
    release: {{ .Release.Name }}
    environment: {{ .Values.environment  }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    app: {{ .Values.service.name }}
    environment: {{ .Values.environment  }}
    