{{- if eq .Values.serviceAccount.enabled true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service.name }}-{{ .Values.environment }}-serviceaccount
  namespace: {{ .Values.namespace }}
  annotations:
 
  {{- if eq .Values.environment "staging" }}
  {{- if eq .Values.region "us-east-1" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArnStaging-us-east-1 }}
  {{- end }}
  {{- if eq .Values.region "us-west-2" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArnStaging-us-west-2 }}
  {{- end }}
  {{- end }}
  
  {{- if eq .Values.environment "testing" }}
  {{- if eq .Values.region "us-east-1" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArnTesting-us-east-1 }}
  {{- end }}
  {{- if eq .Values.region "us-west-2" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArnTesting-us-west-2 }}
  {{- end }}
  {{- end }}
  
  {{- if eq .Values.environment "sandbox" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArnSandbox }}
  {{- end }}
  
  {{- if eq .Values.environment "production" }}
  {{- if eq .Values.region "us-east-1" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArnProduction-us-east-1 }}
  {{- end }}
  {{- if eq .Values.region "us-west-2" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArnProduction-us-west-2 }}
  {{- end }}
  {{- end }}    
{{ end }}
                                                                                                                                                                                                                                                                                                