{{- if eq .Values.serviceAccount.enabled true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service.name }}-{{ .Values.enviroment  }}-serviceAccount
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArn }}
{{ end }}
