{{- if eq .Values.serviceAccount.enabled true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service.name }}-{{ .Values.environment  }}-serviceaccount
  namespace: {{ .Values.namespace }}
  annotations:
  {{- if eq .Values.environment "staging" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArnStaging }}
  {{- end }}
  
  {{- if eq .Values.environment "testing" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArnTesting }}
  {{- end }}
  
  {{- if eq .Values.environment "sandbox" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArnSandbox }}
  {{- end }}
  
  {{- if eq .Values.environment "production" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArnProductionRegion1 }}
  {{- end }}    
{{ end }}
                                                                                                                                                                                                                                                                                                