{{- if eq .Values.istioGateway.enable true }} 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name:  {{ .Values.service.name }}-{{ .Values.namespace }}-{{ .Values.environment  }}-vs
  namespace: {{ .Values.istioGateway.namespace }}
  labels:  
    app: application-bankly
    helm-package: bankly-product
    release: {{ .Release.Name }}
spec:
  hosts:
  {{- if eq .Values.environment "staging" }}
  - {{.Values.service.name }}.{{ .Values.namespace }}.bankly-stg-aws.internal
  {{- end }}
  {{- if eq .Values.environment "testing" }}
  - {{.Values.service.name }}.{{ .Values.namespace }}.bankly-tsg-aws.internal
  {{- end }}  
  {{- if eq .Values.environment "sandbox" }}
  - {{.Values.service.name }}.{{ .Values.namespace }}.bankly-sdb-aws.internal
  {{- end }}
  {{- if or (eq .Values.environment "production-region-1") (eq .Values.environment "production-region-2") }}
  - {{.Values.service.name }}.{{ .Values.namespace }}.bankly-prd-aws.internal
  {{- end }}
  gateways:
  - {{ .Values.istioGateway.name }}
  http:
  {{- if eq .Values.isCanary true }}
  - match:
    - headers:
        x-blky-version:
          exact: canary
    route:
      - destination:
          host: {{ .Values.service.name }}-{{ .Values.environment }}-service.{{ .Values.namespace }}.svc.cluster.local
          subset: canary
  {{- end }}
  - route:
    - destination:
        host: {{ .Values.service.name }}-{{ .Values.environment }}-service.{{ .Values.namespace }}.svc.cluster.local
        subset: safe
      {{- if eq .Values.isCanary true }}
      weight: 90
      {{- else }}
      weight: 100
      {{- end }}
    
    {{- if eq .Values.isCanary true }}
    - destination:
        host: {{ .Values.service.name }}-{{ .Values.environment }}-service.{{ .Values.namespace }}.svc.cluster.local
        subset: canary
      weight: 10
     {{- end }}

    {{- if eq .Values.istioGateway.retriesEnable true }} 
    retries:
    {{- toYaml .Values.istioGateway.retries | nindent 12 }}
    {{- end }}
{{- end }}