{{- if eq .Values.istioGateway.enable true }} 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name:  {{ .Values.service.name }}-virtualservice
  namespace: {{ .Values.istioGateway.namespace }}
  labels:  
    app: application-bankly
    helm-package: bankly-product
    release: {{ .Release.Name }}
    
spec:
  hosts:
  {{- if eq .Values.enviroment "staging" }}
  - {{.Values.service.name }}.{{ .Values.namespace }}.bankly-stg-aws.internal
  {{- end }}
  {{- if eq .Values.enviroment "testing" }}
  - {{.Values.service.name }}.{{ .Values.namespace }}.bankly-tsg-aws.internal
  {{- end }}  
  {{- if eq .Values.enviroment "sandbox" }}
  - {{.Values.service.name }}.{{ .Values.namespace }}.bankly-sdb-aws.internal
  {{- end }}
  {{- if eq .Values.enviroment "production" }}
  - {{.Values.service.name }}.{{ .Values.namespace }}.bankly-prd-aws.internal
  {{- end }}
  gateways:
  - {{ .Values.istioGateway.name }}
  http:
  {{- if eq .Values.isCanary true }}
  - match:
    - headers:
        x-bkly-release-version:
          exact: canary
    route:
    - destination:
        host: {{ .Values.service.name }}-{{ .Values.enviroment }}-service
        subset: canary
  {{- end }}
  - route:
    - destination:
        host: {{ .Values.service.name }}-{{ .Values.enviroment }}-service
        subset: safe
      {{- if eq .Values.isCanary true }}
      weight: 90
      {{- end }}
      {{- if eq .Values.isCanary false }}
      weight: 100
      {{- end }}
    {{- if eq .Values.isCanary true }}
    - destination:
        host: {{ .Values.service.name }}-{{ .Values.enviroment }}-service
        subset: canary
      weight: 10
    {{- end }}

    retries:
      attempts: {{ .Values.istioGateway.retries.attempts }}
      perTryTimeout: {{ .Values.istioGateway.retries.perTryTimeout }}
{{- end }}