apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-{{ .Values.environment  }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: genesis
    helm-package: bankly-backstage
    environment: {{ .Values.environment  }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http
  selector:
    {{- include "bankly-backstage.selectorLabels" . | nindent 4 }}
