# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jobs:
  # first cron
  hello-world:
    image:
      repository: busybox
      tag: 1.28
      imagePullPolicy: IfNotPresent
    schedule: '* * * * *'
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Allow
    restartPolicy: OnFailure
    command:
      - /bin/sh
      - -c
      - date; echo Hello from hello-world job

  # # second cron
  hello-ubuntu:
    image:
      repository: ubuntu
      tag: latest
      imagePullPolicy: Always
    schedule: '*/5 * * * *'
    command: ['/bin/bash']
    args:
      - '-c'
      - 'echo $(date) - hello from ubuntu'
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure

environment: staging
region: us-east-1

service:
  name: test-cron-job

serviceAccount:
  enabled: true
  name:
  awsRoleArnStagingUsEast1: ''
  awsRoleArnStagingUsWest2: ''
  awsRoleArnTestingUsEast1: ''
  awsRoleArnTestingUsWest2: ''
  awsRoleArnSandbox: ''
  awsRoleArnProductionUsEast1: ''
  awsRoleArnProductionUsWest2: ''
