{{- $root := . -}}

{{- range $key, $arrayValue := .Values.curity.runtimes }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "curity.fullname" $root }}-{{ $arrayValue.role }}-runtime
  labels:
    {{- include "curity.labels" $root | nindent 4 }}
    role: {{ include "curity.fullname" $root }}-{{ $arrayValue.role }}-runtime
  {{- with $arrayValue.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not $root.Values.autoscaling.enabled }}
  replicas: {{ $root.Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ $root.Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "curity.name" $root }}
      app.kubernetes.io/instance: {{ $root.Release.Name }}
      role: {{ include "curity.fullname" $root }}-{{ $arrayValue.role }}-runtime
  template:
    metadata:
      labels:
        {{- include "curity.labels" $root | nindent 8 }}
        {{- if $arrayValue.podLabels }}
              {{- $arrayValue.podLabels | toYaml | nindent 8 }}
        {{- end }}
        role: {{ include "curity.fullname" $root }}-{{ $arrayValue.role }}-runtime
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: {{ include "curity.metricsPort" $root | quote }}
        {{- if $arrayValue.podAnnotations }}
              {{- $arrayValue.podAnnotations | toYaml | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ $root.Chart.Name }}-runtime
          image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          args: ["/opt/idsvr/bin/idsvr",
                 "-s", "{{ $arrayValue.role }}",
                 {{- if $root.Values.curity.config.encryptionKey}}"-e","{{ $root.Values.curity.config.encryptionKey}}",{{end -}}
                 "--no-admin"]
          env:
            {{- if $root.Values.curity.config.encryptionKey }}
            - name: CONFIG_ENCRYPTION_KEY
              value: {{ .Values.curity.config.encryptionKey | quote }}
            {{- end }}
            - name: STATUS_CMD_PORT
              value: {{ $root.Values.curity.healthCheckPort | quote }}
            - name: LOGGING_LEVEL
              value: {{ $arrayValue.logging.level }}
            {{- range $env := $arrayValue.extraEnv }}
            - name: {{ $env.name }}
              {{- if $env.value }}
              value: {{ $env.value | quote }}
              {{- end }}
              {{- if $env.valueFrom }}
              valueFrom: {{ $env.valueFrom | toYaml | trim | nindent 16 }}
              {{- end }}
            {{- end }}
          {{- if ( or $root.Values.curity.config.environmentVariableSecret $root.Values.curity.config.environmentVariableConfigMap $root.Values.curity.config.environmentVariableSecrets $root.Values.curity.config.environmentVariableConfigMaps $root.Values.curity.config.convertKeystore ) }}
          envFrom:
          {{- range $configMap := concat $root.Values.curity.config.environmentVariableConfigMaps ( list $root.Values.curity.config.environmentVariableConfigMap ) }}
          {{- if $configMap }}
            - configMapRef:
                name: {{ $configMap | quote }}
          {{- end }}
          {{- end }}
          {{- range $secret := concat $root.Values.curity.config.environmentVariableSecrets ( list $root.Values.curity.config.environmentVariableSecret ) }}
          {{- if $secret }}
            - secretRef:
                name: {{ $secret | quote}}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if $root.Values.curity.config.convertKeystore }}
            - secretRef:
                name: {{ include "curity.fullname" $root }}-convert-ks-secret-envs
          {{- end }}
          ports:
            - name: http-port
              containerPort: {{ $arrayValue.deployment.port }}
              protocol: TCP
            - name: health-check
              containerPort: {{ $root.Values.curity.healthCheckPort }}
              protocol: TCP
            - name: metrics
              containerPort: {{ include "curity.metricsPort" $root }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: health-check
            timeoutSeconds:  {{ $arrayValue.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ $arrayValue.livenessProbe.failureThreshold }}
            periodSeconds: {{ $arrayValue.livenessProbe.periodSeconds }}
            initialDelaySeconds: {{ $arrayValue.livenessProbe.initialDelaySeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: health-check
            timeoutSeconds:  {{ $arrayValue.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ $arrayValue.readinessProbe.failureThreshold }}
            successThreshold: {{ $arrayValue.readinessProbe.successThreshold }}
            periodSeconds: {{ $arrayValue.readinessProbe.periodSeconds }}
            initialDelaySeconds: {{ $arrayValue.readinessProbe.initialDelaySeconds }}
          volumeMounts:
            {{- if $arrayValue.logging.stdout }}
            - mountPath: /opt/idsvr/var/log/
              name: log-volume
            {{- end }}
            - mountPath: /opt/idsvr/etc/init/cluster.xml
              subPath: cluster.xml
              name: cluster-xml
              readOnly: true
            {{- if $root.Values.curity.config.configurationSecret }}
            - mountPath: /opt/idsvr/etc/init/config.xml
              subPath: config.xml
              name: config
              readOnly: true
            {{- end }}
            {{- if $root.Values.curity.config.configurationConfigMap }}
            - mountPath: /opt/idsvr/etc/init/configmap-config.xml
              subPath: {{ required "\n curity.config.configurationConfigMapItemName required when curity.config.configurationConfigMap is set. "  $root.Values.curity.config.configurationConfigMapItemName }}
              name: configmap-config
              readOnly: true
            {{- end }}
            {{- range $conf := $root.Values.curity.config.configuration }}
            {{- if $conf.configMapRef }}
            {{- range $confItem := $conf.configMapRef.items }}
            - mountPath: /opt/idsvr/etc/init/{{ $confItem.path }}
              subPath: {{ $confItem.path }}
              name: {{ $conf.configMapRef.name }}-volume
              readOnly: true
            {{- end }}
            {{- end }}
            {{- if $conf.secretRef }}
            {{- range $confItem := $conf.secretRef.items }}
            - mountPath: /opt/idsvr/etc/init/{{ $confItem.path }}
              subPath: {{ $confItem.path }}
              name: {{ $conf.secretRef.name }}-volume
              readOnly: true
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if $arrayValue.extraVolumeMounts }}
                    {{- $arrayValue.extraVolumeMounts | toYaml | nindent 12 }}
            {{- end }}
          resources:
            {{- if $arrayValue.resources }}
              {{- toYaml $arrayValue.resources | nindent 12 }}
            {{- else }}
              {{- toYaml $root.Values.resources | nindent 12 }}
            {{- end }}
        {{- if $arrayValue.logging.stdout }}
        {{- range $arrayValue.logging.logs }}
        - name: {{ . }}
          image: {{ $arrayValue.logging.image }}
          command:
            - "tail"
            - "-F"
            - "/log/{{ . | lower }}.log"
          volumeMounts:
            - name: log-volume
              mountPath: /log
              readOnly: true
          resources:
            {{- if $arrayValue.logging.resources }}
              {{- toYaml $arrayValue.logging.resources | nindent 12 }}
            {{- else }}
              {{- toYaml $root.Values.logging.resources | nindent 12 }}
            {{- end }}
        {{- end }}
        {{- end }}
      {{- if $root.Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ $root.Values.image.pullSecret}}
      {{- end }}
      volumes:
        {{- if $arrayValue.logging.stdout }}
        - name: log-volume
          emptyDir: {}
        {{- end }}
        - name: cluster-xml
          secret:
            secretName: {{ include "curity.fullname" $root }}-cluster-config-xml
            items:
              - key: cluster-{{ $root.Release.Revision }}.xml
                path: cluster.xml
        {{- if $root.Values.curity.config.configurationSecret }}
        - name: config
          secret:
            secretName: {{ $root.Values.curity.config.configurationSecret }}
            items:
              - key: {{ required "\n curity.config.configurationSecretItemName required when curity.config.configurationSecret is set. " $root.Values.curity.config.configurationSecretItemName }}
                path: config.xml
        {{- end }}
        {{- if $root.Values.curity.config.configurationConfigMap }}
        - name: configmap-config
          configMap:
            name: {{ $root.Values.curity.config.configurationConfigMap }}
        {{- end }}
        {{- range $conf := $root.Values.curity.config.configuration }}
        {{- if $conf.configMapRef }}
        - name: {{ $conf.configMapRef.name }}-volume
          configMap:
            name: {{ $conf.configMapRef.name }}
            items:
              {{- range $confItem := $conf.configMapRef.items }}
              - key: {{ if $confItem.key }}{{ $confItem.key }}{{ else }}{{ $confItem.path }}{{ end }}
                path: {{ $confItem.path }}
              {{- end }}
        {{- end }}
        {{- if $conf.secretRef }}
        - name: {{ $conf.secretRef.name }}-volume
          secret:
            secretName: {{ $conf.secretRef.name }}
            items:
              {{- range $confItem := $conf.secretRef.items }}
              - key: {{ if $confItem.key }}{{ $confItem.key }}{{ else }}{{ $confItem.path }}{{ end }}
                path: {{ $confItem.path }}
              {{- end }}
        {{- end }}
        {{- end }}
        {{- if $arrayValue.extraVolumes }}
              {{- $arrayValue.extraVolumes | toYaml | nindent 8 }}
        {{- end }}
      serviceAccountName: {{ $arrayValue.serviceAccount.name | default "default" | quote }}
      {{- with $arrayValue.initContainers }}
      initContainers:
            {{- toYaml $root | nindent 8 }}
      {{- end }}
      {{- with $root.Values.nodeSelector }}
      nodeSelector:
            {{- toYaml $root | nindent 8 }}
      {{- end }}
      {{- with $root.Values.affinity }}
      affinity:
            {{- toYaml $root | nindent 8 }}
      {{- end }}
      {{- with $root.Values.tolerations }}
      tolerations:
            {{- toYaml $root | nindent 8 }}
      {{- end }}
{{- end }}