{{- if .Values.autoscaling.enabled }}
{{- $root := . -}}

{{- range $key, $arrayValue := .Values.curity.runtimes }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "curity.fullname" $root }}-{{ $arrayValue.role }}-hpa
  labels:
    {{- include "curity.labels" $root | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "curity.fullname" $root }}-{{ $arrayValue.role }}-runtime
  minReplicas: {{ $root.Values.autoscaling.minReplicas }}
  maxReplicas: {{ $root.Values.autoscaling.maxReplicas }}
  metrics:
  {{- if $root.Values.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ $root.Values.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- if $root.Values.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $root.Values.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if $root.Values.autoscaling.customMetrics }}
    {{- $root.Values.autoscaling.customMetrics | toYaml | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
