{{- $root := . -}}

{{- range $key, $arrayValue := .Values.curity.runtimes }}
---
{{- if or $arrayValue.podDisruptionBudget.maxUnavailable $arrayValue.podDisruptionBudget.minAvailable }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "curity.fullname" $root }}-runtime
  namespace: {{ $root.Values.namespace }}
  labels:
    {{- include "curity.labels" $root | nindent 4 }}
    role: {{ include "curity.fullname" $root }}-{{ $arrayValue.role }}-runtime
spec:
  {{- if $arrayValue.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ $arrayValue.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  {{- if $arrayValue.podDisruptionBudget.minAvailable }}
  minAvailable: {{ $arrayValue.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "curity.labels" $root | nindent 6 }}
      role: {{ include "curity.fullname" $root }}-{{ $arrayValue.role }}-runtime
{{- end }}
{{- end }}