{{- $root := . -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "curity.fullname" . }}-service-account
  namespace: {{ $root.Values.namespace }}
  labels:
        {{- include "curity.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "eks.amazonaws.com/role-arn": {{ $root.Values.awsRoleArn}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "curity.fullname" . }}-create-secret
  namespace: {{ $root.Values.namespace }}
  labels:
        {{- include "curity.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "curity.fullname" . }}-role-binding
  namespace: {{ $root.Values.namespace }}
  labels:
        {{- include "curity.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "curity.fullname" . }}-create-secret
subjects:
  - kind: ServiceAccount
    name: {{ include "curity.fullname" . }}-service-account