{{- if eq .Values.istioGateway.enable true }} 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name:  {{ include "curity.fullname" . }}-admin-vs
  namespace: {{ .Values.istioGateway.namespace }}
  labels:
    {{- include "curity.labels" . | nindent 4 }}
    role: {{ include "curity.fullname" . }}-admin
spec:
  hosts:
  - "{{ include "curity.fullname" . }}-admin-vs.{{ .Values.namespace }}bankly-{{ .Values.environment }}-{{ .Values.region }}-aws.internal"
  - "{{ include "curity.fullname" . }}-admin-vs-{{ .Values.environment }}-service.{{ .Values.namespace }}svc.cluster.local"
  gateways:
  - {{ .Values.istioGateway.name }}
  http:
  - route:
    - destination:
        host: "{{ include "curity.fullname" . }}-admin-vs-{{ .Values.environment }}-service.{{ .Values.namespace }}svc.cluster.local"
{{- end }}