{{- $root := . -}}
{{- range $key, $arrayValue := .Values.curity.runtimes }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "curity.fullname" $root }}-{{ $arrayValue.role }}-runtime
  namespace: {{ $root.Values.istioGateway.namespace }}
  labels:
    {{- include "curity.labels" $root | nindent 4 }}
    role: {{ include "curity.fullname" $root }}-{{ $arrayValue.role }}-runtime
spec:
  hosts:
  - "{{ include "curity.fullname" $root }}-{{ $arrayValue.role }}-runtime-vs{{ $root.Values.namespace }}.bankly-{{ $root.Values.environment }}-{{ $root.Values.region }}-aws.internal"
  - "{{ include "curity.fullname" $root }}-{{ $arrayValue.role }}-runtime-vs-{{ $root.Values.environment }}-service.{{ $root.Values.namespace }}svc.cluster.local"
  gateways:
  - {{ $root.Values.istioGateway.name }}
  http:
  - route:
    - destination:
        host: "{{ include "curity.fullname" $root }}-{{ $arrayValue.role }}-runtime-vs-{{ $root.Values.environment }}-service.{{ $root.Values.namespace }}svc.cluster.local"
{{- end }}