replicaCount: 1
namespace: bankly-teste

isCanary: false
enviroment: staging

service:
  name: default-service

containerImage: ivanmds2/stepladder:1.0.33

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /hc
    port: 80
  initialDelaySeconds: 10
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /hc
    port: 80
  initialDelaySeconds: 15
  periodSeconds: 5

hpa:
  cpuAverageUtilization: 70
  memoryAverageUtilization: 70
  minReplicas: 2
  maxReplicas: 15

volumes:
- name: default-service-volume
  configMap:
    name: default-service-configmap
    items:
    - key: stepladder.config
      path: stepladder.config

volumeMounts:
- mountPath: "app/config"
  name: default-service-volume


istioGateway:
  enable: false
  name: "root-platform-istio-gateway"
  namespace: "root-platform"
  retries:
    attempts: 3
    perTryTimeout: 2s

serviceAccount:
  enabled: true
  awsRoleArnStaging: "arn:aws:iam::758565826038:role/staging-core-scouter-role"
  awsRoleArnTesting: ""
  awsRoleArnSandbox: ""
  awsRoleArnProductionRegion1: ""
  awsRoleArnProductionRegion2: ""

configMapData:
  stepladder.config: |
    startup:
      serviceName: "stepladder-test-curity"
      serviceVersion: "1.0.0"
    entrypoints:
      routes:
      - route: "hc"
        method: get
        enableAnonymous: true
        responseMock:
          bodyValue: "{\"status\":\"Healthy\",\"totalDuration\":\"00:00:00.0000606\",\"entries\":{\"self\":{\"status\":\"Healthy\"}}}"
          contentType: "application/json"
          statusCode: 200


stagingEnv:
- name: "CONFIG_APP_PATH"
  value: "config/stepladder.config"
- name: "OTEL_ENABLE_TELEMETRY"
  value: "true"
- name: "OTEL_IS_GRPC"
  value: "false"
- name: "OTEL_ENDPOINT"
  value: "http://otel-http.kube.acesso-stg.aws"
- name: "ENV_FILE"
  value: ""

testingEnv: {}
sandboxEnv: {}
productionEnv: {}

podDisruptionBudget:
  minAvailable: 2

