namespace: default

isCanary: false
environment: staging
region: us-east-1
isArm64: true

service:
  name: default-service

containerImage: nginx:last
containerPort: 80

priorityClassName: medium-priority
 
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /hc
    port: 80
  initialDelaySeconds: 30
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /hc
    port: 80
  initialDelaySeconds: 45
  periodSeconds: 5

hpa:
  cpuAverageUtilization: 70
  memoryAverageUtilization: 70
  minReplicas: 2
  maxReplicas: 15

hpaKeda:
  pollingInterval: 20
  minReplicaCount: 2
  maxReplicaCount: 10 
  triggers: {}

volumes: {}
volumeMounts: {}

istioGateway:
  enable: true
  name: "root-platform-gateway"
  namespace: "root-platform"
  retriesEnable: false
  retries:
    attempts: 3
    perTryTimeout: 2s
    retryOn: '500'
    retryRemoteLocalities: true

serviceAccount:
  enabled: false
  awsRoleArnStagingUsEast1: ""
  awsRoleArnStagingUsWest2: ""
  awsRoleArnTestingUsEast1: ""
  awsRoleArnTestingUsWest2: ""
  awsRoleArnSandbox: ""
  awsRoleArnProductionUsEast1: ""
  awsRoleArnProductionUsWest2: ""

tagResources:
  context: "Platform"
  type: "shared"
  cc: 999
  product: "Gringotts"

configMapData: {}

stagingEnvironment: {}
testingEnvironment: {}
sandboxEnvironment: {}
productionEnvironment: {}

podDisruptionBudget:
  minAvailable: 2
