replicaCount: 1
namespace: default

isCanary: false
enviroment: staging

service:
  name: default-service

image:
  repository: default-repository
  tag: 0.0.1

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

hpa:
  cpuAverageUtilization: 70
  memoryAverageUtilization: 70
  minReplicas: 2
  maxReplicas: 15

istioGateway:
  enable: true
  name: "root-platform-istio-gateway"
  retries:
    attempts: 3
    perTryTimeout: 2s

serviceAccount:
  enabled: true
  awsRoleArn: ""

configMapData: {}

stagingEnv: {}
testingEnv: {}
sandboxEnv: {}
productionEnv: {}

podDisruptionBudget:
  minAvailable: 2