replicaCount: 1
namespace: default

isCanary: false
enviroment: staging

service:
  name: default-service

containerImage: nginx:last

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /hc
    port: 80
  initialDelaySeconds: 10
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /hc
    port: 80
  initialDelaySeconds: 15
  periodSeconds: 5

hpa:
  cpuAverageUtilization: 70
  memoryAverageUtilization: 70
  minReplicas: 2
  maxReplicas: 15

volumes: {}
volumeMounts: {}

istioGateway:
  enable: true
  name: "root-platform-gateway"
  namespace: "root-platform"
  retriesEnable: false
  retries:
    attempts: 3
    perTryTimeout: 2s
    retryOn: '500'
    retryRemoteLocalities: true

serviceAccount:
  enabled: false
  awsRoleArnStaging: ""
  awsRoleArnTesting: ""
  awsRoleArnSandbox: ""
  awsRoleArnProductionRegion1: ""
  awsRoleArnProductionRegion2: ""

configMapData: {}

stagingEnv: {}
testingEnv: {}
sandboxEnv: {}
productionEnv: {}

podDisruptionBudget:
  minAvailable: 2