replicaCount: 1
namespace: default

isCanary: false
enviroment: staging

service:
  name: default-service

image:
  repository: default-repository
  tag: 0.0.1

resources: 
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

istioGateway:
  enable: false

podDisruptionBudget:
  minAvailable: 2
  maxUnavailable: 1
